import type { Page } from "playwright";

export type BridgeCaptureFormState = {
  screen: string | null;
  step: string | null;
  /** Up to 10 mobile digits from ?craftMobile= */
  mobileDigits: string | null;
  /** True when ?craftAgreed=1|true|yes */
  agreed: boolean;
  /** `single` | `married` from ?craftMarital= on tell-us-more step */
  maritalStatus: "single" | "married" | null;
  /** True when citizenship checkboxes were checked at push time */
  tellUsCitizen: boolean;
  /** `draw` | `autogenerated` on signature selection step */
  sigMethod: "draw" | "autogenerated" | null;
  /** True when signature pad already has ink / Save CTA is enabled at push time */
  sigDrawn: boolean;
};

const TRUTHY = new Set(["1", "true", "yes", "on"]);

/** Parse bridge capture query params that mirror live preview form state. */
export function parseBridgeCaptureFormState(captureUrl: string): BridgeCaptureFormState {
  try {
    const parsed = new URL(captureUrl);
    const mobileRaw = parsed.searchParams.get("craftMobile")?.replace(/\D/g, "") ?? "";
    const mobileDigits = mobileRaw.length >= 10 ? mobileRaw.slice(-10) : mobileRaw.length > 0 ? mobileRaw : null;
    const agreedRaw = parsed.searchParams.get("craftAgreed")?.trim().toLowerCase() ?? "";
    const maritalRaw = parsed.searchParams.get("craftMarital")?.trim().toLowerCase() ?? "";
    const maritalStatus =
      maritalRaw === "single" || maritalRaw === "married" ? maritalRaw : null;
    const tellUsCitizenRaw = parsed.searchParams.get("craftTellUsCitizen")?.trim().toLowerCase() ?? "";
    const sigMethodRaw = parsed.searchParams.get("craftSigMethod")?.trim().toLowerCase() ?? "";
    const sigMethod =
      sigMethodRaw === "draw" || sigMethodRaw === "autogenerated" ? sigMethodRaw : null;
    const sigDrawnRaw = parsed.searchParams.get("craftSigDrawn")?.trim().toLowerCase() ?? "";
    return {
      screen: parsed.searchParams.get("screen")?.trim().toLowerCase() ?? null,
      step: parsed.searchParams.get("step")?.trim().toLowerCase() ?? null,
      mobileDigits,
      agreed: TRUTHY.has(agreedRaw),
      maritalStatus,
      tellUsCitizen: TRUTHY.has(tellUsCitizenRaw),
      sigMethod,
      sigDrawn: TRUTHY.has(sigDrawnRaw),
    };
  } catch {
    return {
      screen: null,
      step: null,
      mobileDigits: null,
      agreed: false,
      maritalStatus: null,
      tellUsCitizen: false,
      sigMethod: null,
      sigDrawn: false,
    };
  }
}

function isOnboardingMobileStep(state: BridgeCaptureFormState): boolean {
  return state.screen === "onboarding" && state.step === "mobile";
}

function isOnboardingTellUsMoreStep(state: BridgeCaptureFormState): boolean {
  return state.screen === "onboarding" && state.step === "tell-us-more";
}

function isOnboardingSignatureStep(state: BridgeCaptureFormState): boolean {
  return state.screen === "onboarding" && state.step === "signature";
}

function isOnboardingSignatureDrawStep(state: BridgeCaptureFormState): boolean {
  if (state.screen !== "onboarding") return false;
  const step = state.step ?? "";
  return step === "signature-draw" || step === "sig-draw" || step === "draw-signature";
}

async function waitForOnboardingSignatureStep(page: Page): Promise<void> {
  await page.getByText("Add signature").first().waitFor({ timeout: 10_000 }).catch(() => undefined);
}

async function waitForSignatureDrawStep(page: Page): Promise<void> {
  await page.getByText("Draw your signature").first().waitFor({ timeout: 10_000 }).catch(() => undefined);
}

async function signaturePadHasInk(page: Page): Promise<boolean> {
  return page.evaluate(`() => {
    const canvas = document.querySelector(
      ".ob-flow-sig-draw canvas, .ob-flow-sig-draw__canvas canvas, [class*='sig-draw'] canvas"
    );
    if (canvas instanceof HTMLCanvasElement) {
      try {
        const ctx = canvas.getContext("2d");
        if (ctx && canvas.width > 0 && canvas.height > 0) {
          const data = ctx.getImageData(0, 0, canvas.width, canvas.height).data;
          for (let i = 3; i < data.length; i += 32) {
            if (data[i] > 8) return true;
          }
        }
      } catch (_) {}
    }
    if (document.querySelector(
      "[class*='sig-draw'][class*='--filled'], [class*='sig-draw'][class*='--has-signature'], .ob-flow-sig-draw__box--filled"
    )) {
      return true;
    }
    const btn = document.querySelector(".ob-flow__footer .btn--filled, .ob-flow__footer button.btn");
    if (btn instanceof HTMLButtonElement) {
      const label = (btn.textContent || "").replace(/\\s+/g, " ").trim().toLowerCase();
      if (label.includes("save") && !btn.disabled && !btn.classList.contains("btn--disabled")) {
        return true;
      }
    }
    return false;
  }`);
}

async function drawSampleSignatureStroke(page: Page): Promise<void> {
  const pad = page
    .locator(
      ".ob-flow-sig-draw canvas, .ob-flow-sig-draw__canvas canvas, .ob-flow-sig-draw__box, .ob-flow-sig-draw__pad, [class*='sig-draw'] canvas, [class*='sig-draw'] [class*='__box']",
    )
    .first();
  if ((await pad.count()) === 0) return;

  const box = await pad.boundingBox();
  if (!box || box.width < 8 || box.height < 8) return;

  const startX = box.x + box.width * 0.18;
  const midX = box.x + box.width * 0.52;
  const endX = box.x + box.width * 0.82;
  const baseY = box.y + box.height * 0.58;

  await page.mouse.move(startX, baseY);
  await page.mouse.down();
  await page.mouse.move(startX + box.width * 0.12, baseY - box.height * 0.18, { steps: 8 });
  await page.mouse.move(midX, baseY + box.height * 0.12, { steps: 12 });
  await page.mouse.move(endX, baseY - box.height * 0.08, { steps: 10 });
  await page.mouse.up();

  await page
    .waitForFunction(
      `() => {
        const canvas = document.querySelector(".ob-flow-sig-draw canvas, [class*='sig-draw'] canvas");
        if (canvas instanceof HTMLCanvasElement) {
          try {
            const ctx = canvas.getContext("2d");
            if (ctx && canvas.width > 0 && canvas.height > 0) {
              const data = ctx.getImageData(0, 0, canvas.width, canvas.height).data;
              for (let i = 3; i < data.length; i += 32) {
                if (data[i] > 8) return true;
              }
            }
          } catch (_) {}
        }
        const btn = document.querySelector(".ob-flow__footer .btn--filled, .ob-flow__footer button.btn");
        return btn instanceof HTMLButtonElement && !btn.disabled && !btn.classList.contains("btn--disabled");
      }`,
      { timeout: 4_000 },
    )
    .catch(() => undefined);
}

async function ensureSignatureDrawn(page: Page): Promise<void> {
  if (await signaturePadHasInk(page)) return;
  await drawSampleSignatureStroke(page);
}

async function selectDrawSignatureOption(page: Page): Promise<void> {
  const card = page
    .locator(".ob-flow-sig-option, .ob-flow-signature-option, [class*='sig-option']")
    .filter({ hasText: /draw a signature/i })
    .first();
  if ((await card.count()) === 0) return;
  const selected = await card.evaluate((el) =>
    [...el.classList].some((c) => /--selected\b/.test(c)),
  );
  if (!selected) {
    await card.click({ force: true });
    await page.waitForTimeout(250);
  }
}

async function selectAutogeneratedSignature(page: Page): Promise<void> {
  const card = page
    .locator(".ob-flow-sig-option, .ob-flow-signature-option, [class*='sig-option']")
    .filter({ hasText: /autogenerated/i })
    .first();
  if ((await card.count()) === 0) return;
  const selected = await card.evaluate((el) =>
    [...el.classList].some((c) => /--selected\b/.test(c)),
  );
  if (selected) return;
  await card.click({ force: true });
  await page
    .waitForFunction(
      `() => {
        const cards = document.querySelectorAll('.ob-flow-sig-option, .ob-flow-signature-option, [class*="sig-option"]');
        for (const card of cards) {
          if (![...card.classList].some((c) => /--selected\\b/.test(c))) continue;
          const text = card.textContent?.replace(/\\s+/g, " ").trim().toLowerCase() ?? "";
          if (text.includes("autogenerated")) return true;
        }
        return false;
      }`,
      { timeout: 3_000 },
    )
    .catch(() => undefined);
}

async function waitForOnboardingMobileStep(page: Page): Promise<void> {
  await page.getByText("Enter mobile number").first().waitFor({ timeout: 10_000 }).catch(() => undefined);
}

async function ensureConsentChecked(page: Page): Promise<void> {
  const checkbox = page.locator('.ob-flow-form__tc .checkbox__input, .ob-flow-form__tc input[type="checkbox"]').first();
  if ((await checkbox.count()) === 0) return;
  const checked = await checkbox.isChecked().catch(() => false);
  if (checked) return;
  await checkbox.click({ force: true });
  await page
    .waitForFunction(
      `() => {
        const input = document.querySelector('.ob-flow-form__tc .checkbox__input, .ob-flow-form__tc input[type="checkbox"]');
        return input instanceof HTMLInputElement && input.checked;
      }`,
      { timeout: 3_000 },
    )
    .catch(() => undefined);
}

async function fillMobileNumber(page: Page, digits: string): Promise<void> {
  const input = page
    .locator('.ob-flow-form .textfield__input, .ob-flow-form input[type="text"], .ob-flow-form input[type="tel"]')
    .first();
  if ((await input.count()) === 0) return;

  await input.click({ force: true });
  await input.press("Meta+A").catch(() => input.press("Control+A"));
  await input.press("Backspace").catch(() => undefined);
  await input.pressSequentially(digits, { delay: 25 });

  await page
    .waitForFunction(
      `(expected) => {
        const input = document.querySelector('.ob-flow-form .textfield__input, .ob-flow-form input[type="text"], .ob-flow-form input[type="tel"]');
        if (!(input instanceof HTMLInputElement)) return false;
        const digits = input.value.replace(/\\D/g, "").replace(/^91/, "").slice(0, 10);
        return digits.length === expected.length && digits === expected;
      }`,
      digits,
      { timeout: 3_000 },
    )
    .catch(() => undefined);

  await page
    .waitForSelector(".ob-flow-form .textfield--filled", { timeout: 3_000 })
    .catch(() => undefined);
  await page
    .waitForSelector(".ob-flow-form .textfield__label--float", { timeout: 3_000 })
    .catch(() => undefined);
}

async function waitForEnabledPrimaryCta(page: Page): Promise<void> {
  await page
    .waitForFunction(
      `() => {
        const btn = document.querySelector('.ob-flow__footer .btn--filled, .ob-flow__footer button.btn');
        if (!(btn instanceof HTMLButtonElement)) return false;
        return !btn.disabled && !btn.classList.contains('btn--disabled');
      }`,
      { timeout: 4_000 },
    )
    .catch(() => undefined);
}

async function waitForTellUsMoreStep(page: Page): Promise<void> {
  await page.getByText("Tell us more about you").first().waitFor({ timeout: 10_000 }).catch(() => undefined);
}

async function ensureObFlowChecksChecked(page: Page): Promise<void> {
  const boxes = page.locator('.ob-flow-checks .checkbox__input, .ob-flow-checks input[type="checkbox"]');
  const count = await boxes.count();
  for (let i = 0; i < count; i++) {
    const box = boxes.nth(i);
    const checked = await box.isChecked().catch(() => false);
    if (!checked) await box.click({ force: true });
  }
}

async function selectMaritalStatus(page: Page, status: "single" | "married"): Promise<void> {
  const label = status === "married" ? "Married" : "Single";
  const card = page.locator(".ob-flow-select-card").filter({ hasText: label }).first();
  if ((await card.count()) === 0) return;
  const selected = await card.evaluate(
    (el) => el.classList.contains("ob-flow-select-card--selected"),
  );
  if (selected) return;
  await card.click({ force: true });
  await page
    .waitForFunction(
      `(label) => {
        const cards = document.querySelectorAll('.ob-flow-select-card');
        for (const card of cards) {
          if (!card.classList.contains('ob-flow-select-card--selected')) continue;
          const text = card.querySelector('.ob-flow-select-card__label')?.textContent?.trim() ?? '';
          return text.toLowerCase() === label.toLowerCase();
        }
        return false;
      }`,
      label,
      { timeout: 3_000 },
    )
    .catch(() => undefined);
}

/**
 * Replay live preview form interactions before DOM extract so Craft captures the same
 * checkbox / CTA state the designer sees (not cold-start defaults).
 */
export async function applyBridgeCaptureInteractiveState(
  page: Page,
  captureUrl: string,
): Promise<boolean> {
  const state = parseBridgeCaptureFormState(captureUrl);

  if (isOnboardingSignatureDrawStep(state)) {
    await waitForSignatureDrawStep(page);
    await ensureSignatureDrawn(page);
    await waitForEnabledPrimaryCta(page);
    await page.waitForTimeout(200);
    return true;
  }

  if (isOnboardingSignatureStep(state)) {
    await waitForOnboardingSignatureStep(page);
    if (state.sigMethod === "draw") {
      await selectDrawSignatureOption(page);
      await waitForSignatureDrawStep(page).catch(() => undefined);
      await ensureSignatureDrawn(page);
    } else {
      await selectAutogeneratedSignature(page);
    }
    await waitForEnabledPrimaryCta(page);
    await page.waitForTimeout(200);
    return true;
  }

  if (isOnboardingTellUsMoreStep(state) && (state.maritalStatus || state.tellUsCitizen)) {
    await waitForTellUsMoreStep(page);
    if (state.tellUsCitizen || state.maritalStatus) {
      await ensureObFlowChecksChecked(page);
    }
    if (state.maritalStatus) {
      await selectMaritalStatus(page, state.maritalStatus);
      await waitForEnabledPrimaryCta(page);
    }
    await page.waitForTimeout(200);
    return true;
  }

  if (!isOnboardingMobileStep(state)) return false;
  if (!state.agreed && !state.mobileDigits) return false;

  await waitForOnboardingMobileStep(page);

  if (state.agreed) {
    await ensureConsentChecked(page);
  }

  if (state.mobileDigits && state.mobileDigits.length === 10) {
    await fillMobileNumber(page, state.mobileDigits);
  }

  if (state.agreed && state.mobileDigits?.length === 10) {
    await waitForEnabledPrimaryCta(page);
  }

  await blurActiveTextfield(page);
  await page.waitForTimeout(200);
  return true;
}

async function blurActiveTextfield(page: Page): Promise<void> {
  await page.evaluate(`() => {
    const active = document.activeElement;
    if (active instanceof HTMLElement) active.blur();
    document.body.dispatchEvent(new MouseEvent("mousedown", { bubbles: true }));
    document.body.dispatchEvent(new MouseEvent("mouseup", { bubbles: true }));
  }`);
  await page
    .waitForFunction(
      `() => !document.querySelector('.ob-flow-form .textfield--focus')`,
      { timeout: 2_000 },
    )
    .catch(() => undefined);
}
