/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_craftengine_free: (a: number, b: number) => void;
export const craftengine_applyDocumentOp: (a: number, b: number, c: number) => [number, number];
export const craftengine_applyDocumentOps: (a: number, b: number, c: number) => [number, number];
export const craftengine_atlasImageCount: (a: number) => number;
export const craftengine_backendLabel: (a: number) => [number, number];
export const craftengine_canRedo: (a: number) => number;
export const craftengine_canUndo: (a: number) => number;
export const craftengine_clearHistory: (a: number) => void;
export const craftengine_create: (a: any) => any;
export const craftengine_hitTest: (a: number, b: number, c: number) => [number, number];
export const craftengine_layoutTextNode: (a: number, b: number, c: number) => [number, number, number, number];
export const craftengine_loadDocument: (a: number, b: number, c: number) => [number, number];
export const craftengine_pushHistorySnapshot: (a: number) => [number, number];
export const craftengine_redo: (a: number) => [number, number];
export const craftengine_registerFontFamily: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const craftengine_registerImageAsset: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const craftengine_render: (a: number) => [number, number];
export const craftengine_resize: (a: number, b: number, c: number, d: number) => void;
export const craftengine_setViewport: (a: number, b: number, c: number, d: number) => void;
export const craftengine_snapshotDocument: (a: number) => [number, number];
export const craftengine_syncDocument: (a: number, b: number, c: number) => [number, number];
export const craftengine_tileCacheLen: (a: number) => number;
export const craftengine_undo: (a: number) => [number, number];
export const engine_version: () => [number, number];
export const init_panic_hook: () => void;
export const wasm_bindgen__convert__closures_____invoke__h9c64e57416b714de: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h897d89226e528b54: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
