/** Open-source families served by Google Fonts (SIL/OFL/etc.). */
export type GoogleFontCategory = "sans-serif" | "serif" | "monospace" | "display" | "handwriting";

export type GoogleFontEntry = {
  name: string;
  category: GoogleFontCategory;
};

function g(name: string, category: GoogleFontCategory = "sans-serif"): GoogleFontEntry {
  return { name, category };
}

export const GOOGLE_FONTS: GoogleFontEntry[] = [
  g("Roboto"),
  g("Open Sans"),
  g("Noto Sans"),
  g("Lato"),
  g("Montserrat"),
  g("Roboto Condensed"),
  g("Source Sans 3"),
  g("Oswald", "display"),
  g("Raleway"),
  g("Poppins"),
  g("Inter"),
  g("Roboto Mono", "monospace"),
  g("Nunito"),
  g("Ubuntu"),
  g("Rubik"),
  g("Work Sans"),
  g("PT Sans"),
  g("Merriweather", "serif"),
  g("Playfair Display", "serif"),
  g("Noto Serif", "serif"),
  g("Mukta"),
  g("Kanit", "display"),
  g("Fira Sans"),
  g("Quicksand"),
  g("Barlow"),
  g("Heebo"),
  g("Titillium Web"),
  g("Libre Franklin"),
  g("Mulish"),
  g("IBM Plex Sans"),
  g("Manrope"),
  g("DM Sans"),
  g("Outfit"),
  g("Plus Jakarta Sans"),
  g("Figtree"),
  g("Space Grotesk"),
  g("Sora"),
  g("Urbanist"),
  g("Archivo"),
  g("Exo 2"),
  g("Josefin Sans"),
  g("Cabin"),
  g("Karla"),
  g("Hind"),
  g("Arimo"),
  g("Overpass"),
  g("Signika"),
  g("Asap"),
  g("Red Hat Display"),
  g("Red Hat Text"),
  g("Public Sans"),
  g("Lexend"),
  g("Commissioner"),
  g("Atkinson Hyperlegible"),
  g("Source Serif 4", "serif"),
  g("Lora", "serif"),
  g("PT Serif", "serif"),
  g("Libre Baskerville", "serif"),
  g("EB Garamond", "serif"),
  g("Crimson Text", "serif"),
  g("Bitter", "serif"),
  g("Cormorant Garamond", "serif"),
  g("Spectral", "serif"),
  g("Cardo", "serif"),
  g("Vollkorn", "serif"),
  g("Domine", "serif"),
  g("IBM Plex Serif", "serif"),
  g("Literata", "serif"),
  g("Fraunces", "serif"),
  g("Newsreader", "serif"),
  g("Inconsolata", "monospace"),
  g("Source Code Pro", "monospace"),
  g("JetBrains Mono", "monospace"),
  g("Fira Code", "monospace"),
  g("Space Mono", "monospace"),
  g("Ubuntu Mono", "monospace"),
  g("Courier Prime", "monospace"),
  g("IBM Plex Mono", "monospace"),
  g("Anonymous Pro", "monospace"),
  g("Bebas Neue", "display"),
  g("Anton", "display"),
  g("Righteous", "display"),
  g("Lobster", "display"),
  g("Pacifico", "handwriting"),
  g("Dancing Script", "handwriting"),
  g("Caveat", "handwriting"),
  g("Satisfy", "handwriting"),
  g("Great Vibes", "handwriting"),
  g("Shadows Into Light", "handwriting"),
  g("Amatic SC", "handwriting"),
  g("Indie Flower", "handwriting"),
  g("Permanent Marker", "handwriting"),
  g("Comfortaa"),
  g("Varela Round"),
  g("M PLUS Rounded 1c"),
  g("ABeeZee"),
  g("Acme"),
  g("Alegreya", "serif"),
  g("Alegreya Sans"),
  g("Almarai"),
  g("Amiri", "serif"),
  g("Andika"),
  g("Archivo Black", "display"),
  g("Arvo", "serif"),
  g("Assistant"),
  g("Bangers", "display"),
  g("Barlow Condensed"),
  g("BenchNine"),
  g("Bodoni Moda", "serif"),
  g("Bree Serif", "serif"),
  g("Cairo"),
  g("Cantarell"),
  g("Catamaran"),
  g("Chakra Petch"),
  g("Chivo"),
  g("Cinzel", "serif"),
  g("Cookie", "handwriting"),
  g("Crete Round", "serif"),
  g("Cuprum"),
  g("DM Serif Display", "serif"),
  g("Dosis"),
  g("Encode Sans"),
  g("Epilogue"),
  g("Exo"),
  g("Familjen Grotesk"),
  g("Farro"),
  g("Fjalla One", "display"),
  g("Frank Ruhl Libre", "serif"),
  g("Gelasio", "serif"),
  g("Genos"),
  g("Gothic A1"),
  g("Gruppo", "display"),
  g("Hanken Grotesk"),
  g("Hind Madurai"),
  g("Hind Siliguri"),
  g("IBM Plex Sans Condensed"),
  g("Inria Sans"),
  g("Inria Serif", "serif"),
  g("Jost"),
  g("Kalam", "handwriting"),
  g("Khand"),
  g("Kreon", "serif"),
  g("Lalezar", "display"),
  g("Lemonada"),
  g("Libre Caslon Text", "serif"),
  g("Lilita One", "display"),
  g("Lobster Two", "display"),
  g("Mada"),
  g("Martel", "serif"),
  g("Maven Pro"),
  g("Merriweather Sans"),
  g("Metrophobic"),
  g("Mitr"),
  g("Monda"),
  g("Nanum Gothic"),
  g("Nanum Myeongjo", "serif"),
  g("Neuton", "serif"),
  g("Niramit"),
  g("Noticia Text", "serif"),
  g("Noto Sans JP"),
  g("Noto Sans KR"),
  g("Noto Sans TC"),
  g("Noto Sans Arabic"),
  g("Noto Sans Devanagari"),
  g("Noto Sans Bengali"),
  g("Noto Sans Tamil"),
  g("Noto Sans Thai"),
  g("Nunito Sans"),
  g("Old Standard TT", "serif"),
  g("Oleo Script", "display"),
  g("Orbitron", "display"),
  g("Oxygen"),
  g("Padauk"),
  g("Palanquin"),
  g("Passion One", "display"),
  g("Pathway Gothic One"),
  g("Patua One", "display"),
  g("Paytone One", "display"),
  g("Philosopher"),
  g("Piazzolla", "serif"),
  g("Podkova", "serif"),
  g("Pontano Sans"),
  g("Prata", "serif"),
  g("Prompt"),
  g("Proza Libre"),
  g("Questrial"),
  g("Rajdhani"),
  g("Rasa", "serif"),
  g("Recursive"),
  g("Rokkitt", "serif"),
  g("Rowdies", "display"),
  g("Russo One", "display"),
  g("Saira"),
  g("Sanchez", "serif"),
  g("Sarabun"),
  g("Sawarabi Gothic"),
  g("Sawarabi Mincho", "serif"),
  g("Secular One"),
  g("Sen"),
  g("Share Tech"),
  g("Shippori Mincho", "serif"),
  g("Silkscreen", "display"),
  g("Six Caps", "display"),
  g("Slabo 13px", "serif"),
  g("Slabo 27px", "serif"),
  g("Sometype Mono", "monospace"),
  g("Spartan"),
  g("Spectral SC", "serif"),
  g("Staatliches", "display"),
  g("Stick No Bills"),
  g("Syne"),
  g("Tajawal"),
  g("Taviraj", "serif"),
  g("Teko"),
  g("Tenor Sans"),
  g("Tinos", "serif"),
  g("Tourney", "display"),
  g("Trirong", "serif"),
  g("Truculenta"),
  g("Unbounded"),
  g("Unna", "serif"),
  g("Varta"),
  g("Vazirmatn"),
  g("Volkhov", "serif"),
  g("Vollkorn SC", "serif"),
  g("Yanone Kaffeesatz"),
  g("Yantramanav"),
  g("Yatra One", "display"),
  g("Yellowtail", "handwriting"),
  g("Yeseva One", "display"),
  g("Yrsa", "serif"),
  g("Zilla Slab", "serif"),
];

export function googleFontFallback(category: GoogleFontCategory): string {
  switch (category) {
    case "serif":
      return "Georgia, serif";
    case "monospace":
      return "ui-monospace, monospace";
    case "display":
    case "handwriting":
      return "system-ui, sans-serif";
    default:
      return "system-ui, sans-serif";
  }
}

export function cssFamilyForGoogleFont(entry: GoogleFontEntry): string {
  return `"${entry.name}", ${googleFontFallback(entry.category)}`;
}
